version: "3.7"

services:
  app:
    build: ./docker
    image: thecodeholic/php_mvc
    ports:
      - "8080:80"
    volumes:
   
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
      
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: framework
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  mysql-data: